# @package _global_
name: ice_experiment

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_config: spectral_npe_ice,raw_fmpe_ice, spectral_fmpe_ice,raw_npe_ice
      data_config.n_train: 100,1000,10000,100000
      +run_name: 1, 2, 3


  run:
    dir: ${out_dir}/${name}/${model_config.name}
  sweep:
    dir: ${out_dir}/${name}/${model_config.name}
    subdir: num_sim_${data_config.n_train}_run_${run_name}


defaults:
  - _self_
  - override /hydra/launcher: submitit_slurm
  - override /partition: cpu