# @package _global_
name: linear_gaussian_experiment

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_config: raw_fmpe_linear_gaussian, spectral_fmpe_linear_gaussian, spectral_npe_linear_gaussian
      data_config.n_train: 100, 1000, 10000, 100000
      +run_name: 1, 2, 3

  run:
    dir: ${out_dir}/${name}/${model_config.name}
  sweep:
    dir: ${out_dir}/${name}/${model_config.name}
    subdir: num_sim_${data_config.n_train}_run_${run_name}


defaults:
  - _self_
  - override /launcher: slurm
  - override /partition: gpu