# @package _global_
name: sir_experiment

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_config: fnope_sir
      data_config.n_train: 1000,10000,100000
      evaluation_config.n_cond: 40
      evaluation_config.use_simformer_initial_conditions: True
      +run_name: 1, 2, 3


  run:
    dir: ${out_dir}/${name}
  sweep:
    dir: ${out_dir}/${name}/${model_config.name}
    subdir: num_sim_${data_config.n_train}_run_${run_name}


defaults:
  - _self_
  - override /hydra/launcher: submitit_slurm
  - override /partition: gpu