# evaluation
n_cond: 40 #number of conditioning points for evaluation
num_posterior_samples: 1000
n_sbc: 100
n_tarp: 100
n_predictive_samples: 100
n_predictive_posterior_samples: 1000
use_simformer_initial_conditions: True