workspace: local

# Output directory for results
hydra:
  run:
    dir: ${out_dir}/${data_config.name}/${model_config.name}/debug

  output_subdir: .

defaults:
  - /base_paths
  - data_config: darcy_snr_30
  - model_config: spectral_fmpe_darcy
  - evaluation_config: darcy
  - launcher: local
  - partition: none
  - sweep: darcy_baseline_sbi_sweep #uncomment when launching multirun jobs
  - _self_ # primary config file (THIS) overrides the default config files

