
workspace: local

# Output directory for results
hydra:
  run:
    dir: ${out_dir}/${data_config.name}/${model_config.name}/debug

  output_subdir: .

defaults:
  - /base_paths
  - data_config: ice
  - model_config: fnope_ice
  - evaluation_config: ice
  - launcher: local
  - partition: none
  - sweep: ice_fnope_sweep #uncomment when launching multirun jobs
  - _self_ # primary config file (THIS) overrides the default config files

