# model
name: FNOPE

modes: 10
conv_channels: 16
ctx_embedding_channels: 8
time_embedding_channels: 4
position_embedding_channels: 4
num_layers: 5
always_equispaced: False
training_point_noise:
  jitter: 0.0
  target_gridsize: 1000
# optimization
batch_size: 200
learning_rate: 1e-3
max_num_epochs: 1000
validation_fraction: 0.1
stop_after_epochs: 50

