name: raw_FMPE

#data representation
data_representation: "raw" # "fourier" or "raw", only used for theta atm!
n_fft_modes: 50 # not used for "raw" but keep for config
pad_width: 200 # not used for "raw" but keep for config

#model config
method: "fmpe"
model_type: "mlp"
num_blocks: 5 #only used for resnet
num_layers: 5 #only used for mlp
hidden_features: 64
num_freqs: 16


#embedding config
embedding: "cnn" # "cnn" or "fc"
embedding_dim: 50
num_conv_layers: 2
num_linear_layers: 2
num_linear_units: 50
kernel_size: 5
out_channels_per_layer: [6,12]
pool_kernel_size: 2

# optimization
batch_size: 200
learning_rate: 1e-4