name: spectral_NPE


#data representation
data_representation: "fourier" # "fourier" or "raw", only used for theta atm!
n_fft_modes: 50 # number of fourier modes to use
pad_width: 200


#model config
method: "npe"

#embedding config
embedding: "fc" # "cnn" or "fc"
embedding_dim: 40
embedding_num_layers: 2
embedding_hidden_dim: 50


# optimization
batch_size: 200