name: linear_gaussian
data_path: 'linear_gaussian'
train_data: 'linear_gaussian_v0_train.pkl'
test_data: 'linear_gaussian_v0_test.pkl'
experiment_name: 'linear_gaussian'
#n_train: 10000 # if n_train<0: use all available training data. 
n_train: 100


defaults:
  - _self_