# @package _global_

defaults:
  - _self_
  - override /hydra/launcher: submitit_slurm


hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    timeout_min: 600
    cpus_per_task: 4
    gpus_per_node: null
    tasks_per_node: 1
    mem_gb: 32
    nodes: 1
    name: ${hydra.job.name}
    partition: 2080-galvani
    qos: null
    comment: null
    constraint: null
    exclude: galvani-cn221
    gres: gpu
    cpus_per_gpu: null
    gpus_per_task: null
    mem_per_gpu: null
    mem_per_cpu: null
    account: null
    signal_delay_s: 60
    max_num_timeout: 0
    additional_parameters: {}
    array_parallelism: 256
    setup: null